//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _025_Kutuphane
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitapTur
    {
        public int kitapID { get; set; }
        public int turID { get; set; }
        public string tanim { get; set; }
    
        public virtual Tur Tur { get; set; }
        public virtual Kitap Kitap { get; set; }
    }
}
