//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _025_Kutuphane
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KutuphaneEntities : DbContext
    {
        public KutuphaneEntities()
            : base("name=KutuphaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Duyuru> Duyurus { get; set; }
        public virtual DbSet<KitapTur> KitapTurs { get; set; }
        public virtual DbSet<KitapYazar> KitapYazars { get; set; }
        public virtual DbSet<Odunc> Oduncs { get; set; }
        public virtual DbSet<Tur> Turs { get; set; }
        public virtual DbSet<Uye> Uyes { get; set; }
        public virtual DbSet<Yazar> Yazars { get; set; }
        public virtual DbSet<viewKitap> viewKitaps { get; set; }
        public virtual DbSet<Kitap> Kitaps { get; set; }
    }
}
