//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _025_Kutuphane
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odunc
    {
        public int oduncID { get; set; }
        public Nullable<int> kitapID { get; set; }
        public Nullable<int> uyeID { get; set; }
        public System.DateTime vermeTarihi { get; set; }
        public int vermeSuresi { get; set; }
        public Nullable<bool> geldiMi { get; set; }
    
        public virtual Uye Uye { get; set; }
        public virtual Kitap Kitap { get; set; }
    }
}
