//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _025_Kutuphane
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewKitap
    {
        public int kitapID { get; set; }
        public string kitapAdi { get; set; }
        public string ISBN { get; set; }
        public int sayfaSayisi { get; set; }
        public string ozet { get; set; }
        public string kitapResim { get; set; }
        public int kitapSayisi { get; set; }
        public int yazarID { get; set; }
        public string yazarAdi { get; set; }
        public string turAciklama { get; set; }
    }
}
