//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _025_Kutuphane.ServiceReferenceKitapAra {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceKitapAra.WebServiceKitapAraSoap")]
    public interface WebServiceKitapAraSoap {
        
        // CODEGEN: Generating message contract since element name prefix from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoktorGetir", ReplyAction="*")]
        _025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirResponse DoktorGetir(_025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoktorGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<_025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirResponse> DoktorGetirAsync(_025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoktorGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoktorGetir", Namespace="http://tempuri.org/", Order=0)]
        public _025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirRequestBody Body;
        
        public DoktorGetirRequest() {
        }
        
        public DoktorGetirRequest(_025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoktorGetirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prefix;
        
        public DoktorGetirRequestBody() {
        }
        
        public DoktorGetirRequestBody(string prefix) {
            this.prefix = prefix;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoktorGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoktorGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public _025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirResponseBody Body;
        
        public DoktorGetirResponse() {
        }
        
        public DoktorGetirResponse(_025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoktorGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _025_Kutuphane.ServiceReferenceKitapAra.ArrayOfString DoktorGetirResult;
        
        public DoktorGetirResponseBody() {
        }
        
        public DoktorGetirResponseBody(_025_Kutuphane.ServiceReferenceKitapAra.ArrayOfString DoktorGetirResult) {
            this.DoktorGetirResult = DoktorGetirResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceKitapAraSoapChannel : _025_Kutuphane.ServiceReferenceKitapAra.WebServiceKitapAraSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceKitapAraSoapClient : System.ServiceModel.ClientBase<_025_Kutuphane.ServiceReferenceKitapAra.WebServiceKitapAraSoap>, _025_Kutuphane.ServiceReferenceKitapAra.WebServiceKitapAraSoap {
        
        public WebServiceKitapAraSoapClient() {
        }
        
        public WebServiceKitapAraSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceKitapAraSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceKitapAraSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceKitapAraSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirResponse _025_Kutuphane.ServiceReferenceKitapAra.WebServiceKitapAraSoap.DoktorGetir(_025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirRequest request) {
            return base.Channel.DoktorGetir(request);
        }
        
        public _025_Kutuphane.ServiceReferenceKitapAra.ArrayOfString DoktorGetir(string prefix) {
            _025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirRequest inValue = new _025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirRequest();
            inValue.Body = new _025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirRequestBody();
            inValue.Body.prefix = prefix;
            _025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirResponse retVal = ((_025_Kutuphane.ServiceReferenceKitapAra.WebServiceKitapAraSoap)(this)).DoktorGetir(inValue);
            return retVal.Body.DoktorGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirResponse> _025_Kutuphane.ServiceReferenceKitapAra.WebServiceKitapAraSoap.DoktorGetirAsync(_025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirRequest request) {
            return base.Channel.DoktorGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<_025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirResponse> DoktorGetirAsync(string prefix) {
            _025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirRequest inValue = new _025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirRequest();
            inValue.Body = new _025_Kutuphane.ServiceReferenceKitapAra.DoktorGetirRequestBody();
            inValue.Body.prefix = prefix;
            return ((_025_Kutuphane.ServiceReferenceKitapAra.WebServiceKitapAraSoap)(this)).DoktorGetirAsync(inValue);
        }
    }
}
